spring:
  config:
    name: sixthproject
  datasource:
    url: jdbc:postgresql://localhost:5432/dbcosmetic
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: false
      path: /h2-console
server:
  port: 8080

jwt:
  secret: myVerySecretKeyThatIsLongEnoughForJWTAlgorithmSecurityRequirements123456789
  expiration: 86400

logging:
  level:
    com.example.fifthproject: DEBUG
    org.springframework.security: DEBUG




